# Generated by Django 2.1.7 on 2020-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=64, verbose_name='项目id')),
                ('name', models.CharField(max_length=200, verbose_name='回调描述')),
                ('request_uri', models.CharField(max_length=200, verbose_name='请求接口')),
                ('request_body', models.TextField(verbose_name='请求BODY')),
                ('pragram', models.CharField(max_length=200, verbose_name='可变参数')),
                ('status', models.CharField(max_length=200, verbose_name='回调状态')),
            ],
            options={
                'verbose_name': 'MOCK回调管理',
                'verbose_name_plural': 'MOCK回调管理',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=64, verbose_name='方法名')),
                ('type', models.CharField(max_length=200, verbose_name='mock类型')),
                ('value', models.TextField(verbose_name='方法内容')),
                ('value_py', models.TextField(verbose_name='方法内容')),
            ],
            options={
                'verbose_name': 'MOCK方法管理',
                'verbose_name_plural': 'MOCK方法管理',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='mock类型')),
                ('method_id', models.CharField(max_length=200, verbose_name='mock_id')),
                ('name', models.CharField(max_length=200, verbose_name='mock名称')),
                ('request_url', models.CharField(max_length=200, verbose_name='请求URL')),
                ('request_body', models.TextField(verbose_name='请求BODY')),
                ('request_method', models.CharField(max_length=200, verbose_name='HTTP类型')),
                ('response', models.TextField(verbose_name='请求响应')),
                ('creat_time', models.DateField(max_length=200, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': 'MOCK请求日志',
                'verbose_name_plural': 'MOCK请求日志',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=64, verbose_name='项目id')),
                ('name', models.CharField(max_length=200, verbose_name='请求描述')),
                ('uri', models.CharField(max_length=200, verbose_name='请求接口')),
                ('route', models.CharField(max_length=200, verbose_name='请求路由')),
                ('type', models.CharField(max_length=200, verbose_name='请求类型')),
                ('result', models.TextField(verbose_name='mock结果')),
                ('pragram', models.CharField(max_length=200, verbose_name='请求参数')),
            ],
            options={
                'verbose_name': 'MOCK请求管理',
                'verbose_name_plural': 'MOCK请求管理',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('project', models.CharField(max_length=200, verbose_name='项目标识')),
                ('rule', models.TextField(verbose_name='项目规则_php')),
                ('rule_py', models.TextField(verbose_name='项目规则_python')),
            ],
            options={
                'verbose_name': 'MOCK项目管理',
                'verbose_name_plural': 'MOCK项目管理',
            },
        ),
    ]
